name: jymu
description: "Training tracking app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  cupertino_onboarding: ^1.2.0
  super_cupertino_navigation_bar: ^2.1.2
  dashed_circular_progress_bar: ^0.0.6
  glassmorphism_ui: ^0.3.0
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  image_picker: ^1.1.2
  firebase_core_platform_interface: ^5.0.0
  cached_network_image: ^3.2.3
  sqflite: ^2.3.3+2
  firebase_auth: ^4.4.2
  uuid: ^4.0.0
  timeago: ^3.1.0
  shared_preferences: ^2.0.0
  flutter_swiper_view: ^1.1.8
  path_provider: ^2.1.4
  fade_shimmer: ^2.2.0
  haptic_feedback: ^0.5.1+1
  auto_size_text: ^3.0.0
  lottie: ^2.0.0
  camera: ^0.10.5+2
  image_cropper: ^4.0.1
  provider: ^6.0.5
  share_plus: ^7.0.2
  url_launcher: ^6.1.10
  palette_generator: ^0.3.3+4
  image: ^4.2.0
  tiktoklikescroller: ^0.2.8
  video_player: ^2.9.1
  animated_page_transition: ^0.0.1+2
  preload_page_view: ^0.2.0
  firebase_messaging: ^14.9.4
  cloud_functions: ^4.7.6
  path: ^1.9.0
  hugeicons: ^0.0.7
  iconsax: ^0.0.8
  #flutter_native_splash: ^2.4.2

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
